export const CANDIDATE_LIST_REQUEST = "CANDIDATE_LIST_REQUEST"
export const CANDIDATE_LIST_SUCCESS = "CANDIDATE_LIST_SUCCESS"
export const CANDIDATE_LIST_FAILURE = "CANDIDATE_LIST_FAILURE"

export const ELECTION_CANDIDATE_REQUEST = "ELECTION_CANDIDATE_REQUEST"
export const ELECTION_CANDIDATE_SUCCESS = "ELECTION_CANDIDATE_SUCCESS"
export const ELECTION_CANDIDATE_FAILURE = "ELECTION_CANDIDATE_FAILURE"

export const VOTE_REQUEST = "VOTE_REQUEST"
export const VOTE_SUCCESS = "VOTE_SUCCESS"
export const VOTE_FAILURE = "VOTE_FAILURE"
