export const RESTAURENT_LIST_REQUEST = 'RESTAURENT_LIST_REQUEST'
export const RESTAURENT_LIST_SUCCESS = 'RESTAURENT_LIST_SUCCESS'
export const RESTAURENT_LIST_FAILURE = 'RESTAURENT_LIST_FAILURE'

export const RESTAURENT_AMBIENCE_LIST_REQUEST = 'RESTAURENT_AMBIENCE_LIST_REQUEST'
export const RESTAURENT_AMBIENCE_LIST_SUCCESSS = 'RESTAURENT_AMBIENCE_LIST_SUCCESSS'
export const RESTAURENT_AMBIENCE_LIST_FAILURE = 'RESTAURENT_AMBIENCE_LIST_FAILURE'

export const RESTAURENT_CUISINE_LIST_REQUEST = 'RESTAURENT_CUISINE_LIST_REQUEST'
export const RESTAURENT_CUISINE_LIST_SUCCESS = 'RESTAURENT_CUISINE_LIST_SUCCESS'
export const RESTAURENT_CUISINE_LIST_FAILURE = 'RESTAURENT_CUISINE_LIST_FAILURE'

export const RESTAURENT_MENU_LIST_REQUEST = 'RESTAURENT_MENU_LIST_REQUEST'
export const RESTAURENT_MENU_LIST_SUCCESS = 'RESTAURENT_MENU_LIST_SUCCESS'
export const RESTAURENT_MENU_LIST_FAILURE = 'RESTAURENT_MENU_LIST_FAILURE'